site_name: BlaBla
pages:
- [index.md, Home]
- [basic-communication.md, 1. Basic communication]
- [authentication.md, 2. Authentication]
- [common-use-cases.md, 3. Common use cases]
- [endpoints/index.md, 4. Endpoints, Endpoints]
- [endpoints/beacon.md, 4. Endpoints, 'Beacon']
- [endpoints/scan-results.md, 4. Endpoints, 'Scan results']
