site_name: Sensimity API Documentation
theme_dir: 'sensimity'
pages:
- [index.md, Home]
- [basic-communication.md, 1. Basic communication]
- [authentication.md, 2. Authentication]
- [common-use-cases.md, 3. Common use cases]
- [endpoints/index.md, 4. Endpoints, Endpoints]
- [endpoints/beacon.md, 4. Endpoints, 'Beacon']
- [endpoints/user.md, 4. Endpoints, 'User']
- [endpoints/scan-results.md, 4. Endpoints, 'Scan result']
- [endpoints/business-rule.md, 4. Endpoints, 'Business rule']
- [endpoints/network.md, 4. Endpoints, 'Network']
